name: Unit Testing
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npx jest --testMatch="**/*.test.js"

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unit-test-results
          path: |
            reports/junit.xml
            coverage

      - name: Publish Unit Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Unit Tests
          path: reports/junit.xml
          reporter: jest-junit
