name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      # --------------------------
      # STEP 1: MAIN BRANCH RUN — generate & upload baseline
      # --------------------------
      - name: Run Jest and upload coverage (main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          npx jest --coverage --coverageReporters=json-summary
        continue-on-error: false

      - name: Upload base coverage
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: base-coverage
          path: coverage/coverage-summary.json

      # --------------------------
      # STEP 2: PR RUN — download & compare
      # --------------------------
      - name: Download base coverage
        if: github.event_name == 'pull_request'
        uses: actions/download-artifact@v4
        with:
          name: base-coverage
          path: coverage-base
        continue-on-error: true

      - name: Run Jest on PR branch
        if: github.event_name == 'pull_request'
        run: |
          npx jest --coverage --coverageReporters=json-summary
          mkdir -p coverage-new
          mv coverage/coverage-summary.json coverage-new/coverage-summary.json

      - name: Compare coverage increase
        if: github.event_name == 'pull_request'
        run: |
          node ./scripts/check-coverage-delta.js
